### ISSUE TITLE
Gamma calculation restricted to within block

### ISSUE THREAD

**Issue by IanEisenberg** [paul-buerkner/thurstonianIRT#13]
My understanding of gamma is that it is the difference of item mean utilities. That is, independent of their relationship latent traits, Item_i may just be more preferable to Item_k, which gamma reflects. In the current model gamma is allowed to freely vary rather than being derived from the underlying mu_i and mu_k

As such gamma is an N length vector. If we have 4 blocks each with 3 items we will have a gamma with a length of 12.

The current simulation script (`SIM_TIRT_data`) doesn't do this. Instead it assumes that the gamma values will be the same for each block. So if we had 4 blocks each with 3 items we will have 3 gamma values repeated 4 times. This is not expected or correct functionality I believe.

**Comment by paul-buerkner** [comment]
You are right. Should be fixed now.
