### ISSUE TITLE
(lavaan) Model parameters extraction

### ISSUE THREAD

**Issue by Pozdniakov** [paul-buerkner/thurstonianIRT#15]
Prediction TIRT scores through lavaan is suboptimal: fitting new data with a sample less than ≈25 lavaan returns error, so, I need to include extra respondents to calculate scores for one person. Any ideas how to extract model parameters for faster and more effective prediction?

**Comment by paul-buerkner** [comment]
Thanks for opening this issue. It seems similar to #12 though. Can you check and clarify potential differences between the two requests?

**Comment by Pozdniakov** [comment]
The main difference with #12 is that this one is for `lavaan` version. It seems that extraction of model parameters from lavaan object is possible without rewriting the fitting part of the package (compared to `Stan`). Furthermore, it seems that `lavaan` model prediction can be faster without using `lavaan::lavPredict()`.

**Comment by paul-buerkner** [comment]
Predictions for new data is now possible for lavaan models via argument newdata in the predict method. Is there anything else that needs to be done before closing this issue?

**Comment by topherwhatever** [comment]
I have tried, with real (noisy) data, to use the newdata argument and the resulting fscores are wildly different when predicted "in sample" and "out of sample" (so to speak). I'm going to try it with a batch of simulated data before being more certain, but I'm wary of the newdata argument.

**Comment by paul-buerkner** [comment]
Ok. I don't know how lavaan does it to be honest and I don't want to fiddle with the lavaan internals to improve this. So this will likely turn out to be a lavaan issue. If you want reliable out-of-sample predictions, Stan is probably your safest way at the moment.

**Comment by paul-buerkner** [comment]
I am closing this issue but I would still be interested in the simulative results if you happen to do them anyway.
