### ISSUE TITLE
Add JOSS Badge to README

### ISSUE THREAD

**Issue by mpadge** [paul-buerkner/thurstonianIRT#18]
Just noticed you don't have the JOSS badge on your README - it would be helpful if you could add the badge to link directly to the corresponding article:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01662/status.svg)](https://doi.org/10.21105/joss.01662)

**Comment by paul-buerkner** [comment]
Thank you, I had missed that. The batch is now shown in the README.
