### ISSUE TITLE
How to omit blocks when analyzing a dataframe?

### ISSUE THREAD

**Issue by leonardomose** [paul-buerkner/thurstonianIRT#21]
I have a database with 22 blocks, three items each. However, when analysing the data I do not want to include 9 of this 22 blocks, as some of them have poor psychometric properties.

When I use the `set_blocks` command there is no argument to ignore a particular triplet that I don't want to include when analyzing the model.

Any idea how to solve this?

**Comment by paul-buerkner** [comment]
When adding the blocks together you could choose to simply not include the 9 unwanted blocks. Nobody forces you to add all 22 blocks just because you have them.

**Comment by leonardomose** [comment]
I know, but for example, when using the `make_mplus_code` function, the desired and unwanted triplets are not included in the NAMES section, not even with the exclamation point "!". This can cause a problem, because my dataframe contains 22 triplets, but the generated code only contains 13 triplets of them. In the "MODEL" section, variables start from i1 and go up to i39, which can also cause an error, since the bank goes up to i66.

**Comment by leonardomose** [comment]
> When adding the blocks together you could choose to simply not include the 9 unwanted blocks. Nobody forces you to add all 22 blocks just because you have them.

I know, but for example, when using the make_mplus_code function, the desired and unwanted triplets are not included in the NAMES section, not even with the exclamation point "!". This can cause a problem, because my dataframe includes 22 triplets, but the generated code only contains 13 triplets of them. In the "MODEL" section, variables start from i1 and go up to i39, which can also cause an error, since the bank goes up to i66.

**Comment by leonardomose** [comment]
> When adding the blocks together you could choose to simply not include the 9 unwanted blocks. Nobody forces you to add all 22 blocks just because you have them.

I know, but for example, when using the `make_mplus_code`  function, the desired and unwanted triplets are not included in the NAMES section, not even with the exclamation point "!". This can cause a problem, because my dataframe includes 22 triplets, but the generated code only contains 13 triplets of them. In the "MODEL" section, variables start from i1 and go up to i39, which can also cause an error, since the bank goes up to i66.

**Comment by paul-buerkner** [comment]
I don't think this is a problem since thurstonianIRT takes care of all of this from the R side, that is passing only the right data etc. Unless there is something not actually working in which case I need a minimal reproducible example.

**Comment by paul-buerkner** [comment]
A small addition to better explain things. While Mplus requires all variables in the data to be used or at least named, thurstonianIRT does not. So it simply selects only the used variables and sends only them to mplus.
