### ISSUE TITLE
Standard errors of trait scores

### ISSUE THREAD

**Issue by leonardomose** [paul-buerkner/thurstonianIRT#22]
Hey Paul, one more question.

I'm using `fit_TIRT_lavaan` to fit my model to lavaan. When using the `predict` function, the output does not show the standard errors of the trait scores, unlike the example shown in "How to use Thurstonian IRT". It would be nice if the output displayed the standard errors of the trait scores so that I could compute the reliability of the scores.

**Comment by paul-buerkner** [comment]
To my knowledge, lavaan does not provide such standard errors, but I am happy to stand corrected.

**Comment by leonardomose** [comment]
I will use Stan instead of lavaan in order to obtain standard errors. Thank you Paul.
