### ISSUE TITLE
test.lavaan.R fails

### ISSUE THREAD

**Issue by yrosseel** [paul-buerkner/thurstonianIRT#25]
Hi,
This came up in rev dep checks of lavaan. test.lavaan.R (in /tests/testthat) produces this error:
```r
lavaan ERROR: type must be one of: lv yhat fy
```
This happens when calling
```r
pr_new <- predict(fit, new_sdata)
```
I realized that newdata= is (per default) the second argument in predict(), but not in lavPredict(). So I changed that on the lavaan side (in lavaan dev 0.6-7) .This resulted in a new error:
```r
Error in lav_data_full(data = data, group = group, cluster = cluster,  : 
  lavaan ERROR: missing observed variables in dataset: i1i3 i2i3 i4i5 i5i6 i7i8 i8i9 i10i11 i10i12 i1i2 i4i6 i7i9 i11i12
```
which brings us to the real issue: the data must first be transformed (using make_sem_data()) before calling predict():
```r
new_sdata <- dplyr::filter(sdata, person %in% 1:5)
new_lavaan_sdata <- make_sem_data(new_sdata)
pr_new <- predict(fit, new_lavaan_sdata)
```
Both in the Bernoulli and Gaussian test.
Yves.

**Comment by paul-buerkner** [comment]
I am a little unsure what is happening here since `predict` for lavaan models automatically calls `make_sem_data`. See https://github.com/paul-buerkner/thurstonianIRT/blob/master/R/lavaan.R line 250 ff.

When I run the tests after installing the latest lavaan dev version `0.6-7.1579`, I can run the tests just fine (after changing a seed to avoid some optimizer error).  

Can you check if it works for you with the lasted thurstonianIRT version from github?

**Comment by yrosseel** [comment]
Indeed. After some digging, it turns out that 
1) thurstonianIRT (0.11.0) gave a failed test when running rev dep checks for lavaan 0.6-7 (but this turns out to be due to the convergence issue; changing the seed fixes it)
2) when trying to figure this out (on another machine), I found the solution above worked ... but for some reason that machine still had version 0.9.0 of thurstonianIRT installed (despite updating all packages; there must have been a hiccup there)
3) the model did not converge with lavaan 0.6-6 either, but it did not result in a fatal error (passing all tests)
4) when a model doesn't converge, lavaan 0.6-7 now tries again with different starting values; but in this example, the second attempt generates a NA value, resulting in a fatal error, explaining 1)

So forget about my 'solution'. Changing the seed (as you already did) is enough.

**Comment by paul-buerkner** [comment]
Thank for you checking! Do you need an hotfix of thurstonianIRT on CRAN to get your next lavaan released, or is it ok if the seed fix only stays in the dev version for some time?

**Comment by yrosseel** [comment]
I already submitted 0.6-7 to CRAN, explaining the issue. This requires a human being pressing the 'ok' button, but I expect this will be ok, and then no hotfix is needed. If will let you know if the CRAN folks decide otherwise...

**Comment by paul-buerkner** [comment]
Good. Let's hope for the best!
