### ISSUE TITLE
Items appearing in multiple blocks

### ISSUE THREAD

**Issue by bozhang3** [paul-buerkner/thurstonianIRT#26]
Hi Paul,

I had a forced-choice measure where some statements appeared in multiple blocks. When I used the set_block function, I was told that items in different blocks need to have different names and I can use the "names" argument to equate parameters. However, I am not sure how to use this argument. Could you please provide a simple example to demonstrate how to use this argument to solve the issue? 

Thanks a lot! 

Best,
Bo

**Comment by SamSWebb** [comment]
I have this exact issue too, it would be great to get an update ASAP.

**Comment by paul-buerkner** [comment]
```R
set_block(
  items = c("i1", "i2", "i3"),
  traits = c("A", "B", "C"),
  names = c("item1", "item2", "item3")
) +
  set_block(
    items = c("i4", "i5", "i6"),
    traits = c("A", "B", "C"),
    names = c("item1", "item5", "item3")
  )
```

to make i1 and i3 equal as well as i3 and i6.

**Comment by paul-buerkner** [comment]
Added an example to the doc
