### ISSUE TITLE
Error in fit_TIRT_mplus()

### ISSUE THREAD

**Issue by szzhou4** [paul-buerkner/thurstonianIRT#34]
Hello, when I run the fit_TIRT_mplus() function after following all prior instructions using set_block() and make_TIRT_data(), I get this error:

> fit <- fit_TIRT_mplus(triplets_long)
Error in names(x) <- value : 
  'names' attribute [5] must be the same length as the vector [0]

Could I get some assistance? Thank you!

**Comment by paul-buerkner** [comment]
Can you please provide a minimal reproducible example?

**Comment by szzhou4** [comment]
Thank you, I am pasting my full script (I couldn't attach a .R file) and attaching the raw data. I could not share the original data for privacy reasons, but I generated fake data using the same column names and structure. Hope that helps. 
[TIRTdata.csv](https://github.com/paul-buerkner/thurstonianIRT/files/9684569/TIRTdata.csv)

library(thurstonianIRT)
library(readr)
TIRTdata <- read_csv("TIRTdata.csv")

blocks <-
  set_block(c("i1", "i2", "i3"), traits = c("neur", "extr", "open"),
            signs = c(-1, 1, 1)) +
  set_block(c("i4", "i5", "i6"), traits = c("agre", "cons", "neur"),
            signs = c(1, 1, -1)) +
  set_block(c("i7", "i8", "i9"), traits = c("open", "extr", "agre"),
            signs = c(-1, 1, 1)) +
  set_block(c("i10", "i11", "i12"), traits = c("cons", "open", "neur"),
            signs = c(1, 1, 1)) +
  set_block(c("i13", "i14", "i15"), traits = c("agre", "neur", "extr"),
            signs = c(1, 1, 1)) +
  set_block(c("i16", "i17", "i18"), traits = c("open", "extr", "cons"),
            signs = c(1, -1, -1)) +
  set_block(c("i19", "i20", "i21"), traits = c("extr", "neur", "agre"),
            signs = c(-1, 1, 1)) +
  set_block(c("i22", "i23", "i24"), traits = c("cons", "open", "extr"),
            signs = c(1, 1, -1)) +
  set_block(c("i25", "i26", "i27"), traits = c("open", "neur", "agre"),
            signs = c(1, 1, -1)) +
  set_block(c("i28", "i29", "i30"), traits = c("cons", "neur", "extr"),
            signs = c(-1, 1, 1)) +
  set_block(c("i31", "i32", "i33"), traits = c("extr", "agre", "cons"),
            signs = c(1, 1, 1)) +
  set_block(c("i34", "i35", "i36"), traits = c("neur", "agre", "open"),
            signs = c(-1, 1, -1)) +
  set_block(c("i37", "i38", "i39"), traits = c("extr", "neur", "cons"),
            signs = c(-1, 1, -1)) +
  set_block(c("i40", "i41", "i42"), traits = c("agre", "cons", "open"),
            signs = c(1, 1, 1)) +
  set_block(c("i43", "i44", "i45"), traits = c("extr", "open", "neur"),
            signs = c(1, 1, 1)) +
  set_block(c("i46", "i47", "i48"), traits = c("cons", "neur", "agre"),
            signs = c(1, -1, -1)) +
  set_block(c("i49", "i50", "i51"), traits = c("cons", "agre", "open"),
            signs = c(-1, 1, 1)) +
  set_block(c("i52", "i53", "i54"), traits = c("agre", "extr", "open"),
            signs = c(-1, 1, -1)) +
  set_block(c("i55", "i56", "i57"), traits = c("open", "cons", "neur"),
            signs = c(-1, 1, 1)) +
  set_block(c("i58", "i59", "i60"), traits = c("cons", "agre", "extr"),
            signs = c(1, -1, 1))

triplets_long <- make_TIRT_data(
  data = TIRTdata[,-1], blocks = blocks, direction = "larger",
  format = "pairwise", family = "bernoulli", range = c(0, 1)
)
head(triplets_long)

fit <- fit_TIRT_mplus(triplets_long)
print(fit)

pr <- predict(fit)
head(pr)

**Comment by leonardomose** [comment]
I'm also having the same issue with the fit_TIRT_mplus() function.

**Comment by paul-buerkner** [comment]
Unfortunately, I don't have Mplus on my system anymore so I cannot debug it myself. My suspicion is that in some new Version of Mplus, they have change the output structure, such that thurstonianIRT cannot read in the output properly anymore. but this is only speculation.

I am more than happy to accept a pull request that fixes this issue.

**Comment by MTAmaranth** [comment]
Hi @paul-buerkner, @szzhou4 and @leonardomose, I have similar issues related to this fit_TIRT_mplus() function. 

I suspect that it has something to do with the make_mplus_code() function where we generate mplus syntax. Mplus can only accept <=80 characters per syntax line. So for larger models, some lines in the auto-generated Mplus code may overflow and get truncated which will stop you from even running the analyses at all.

**Comment by MTAmaranth** [comment]
In my case it seems like this line of code is causing the issue:
    mplus_factor_correlations <- collapse(sapply(1:(ntraits - 
        1), function(i) paste0("trait", i, " WITH ", paste0("trait", 
        (i + 1):ntraits, "*0", collapse = " "), ";\n")))

A quick fix is to change collapse = " " into collapse = "\n". 

I hope this helps!

**Comment by paul-buerkner** [comment]
makes sense! thank you! are there other similar lines we shall change?

MT Li ***@***.***> schrieb am Sa., 25. Feb. 2023, 07:58:

**Comment by paul-buerkner** [comment]
Thanks. Should now be fixed.
