### ISSUE TITLE
Error when using the example provided by the R package

### ISSUE THREAD

**Issue by Arizazcq97** [paul-buerkner/thurstonianIRT#38]
When I use the fit_TIRT_mplus function, I first refer to the example provided by the R package. But when I run the provided example, I get an error. This error is the same as when I run my own data. Can you help me find out what the problem is?
`
# load the data
data("triplets")
# define the blocks of items
blocks <-
  set_block(c("i1", "i2", "i3"), traits = c("t1", "t2", "t3"),
            signs = c(1, 1, 1)) +
  set_block(c("i4", "i5", "i6"), traits = c("t1", "t2", "t3"),
            signs = c(-1, 1, 1)) +
  set_block(c("i7", "i8", "i9"), traits = c("t1", "t2", "t3"),
            signs = c(1, 1, -1)) +
  set_block(c("i10", "i11", "i12"), traits = c("t1", "t2", "t3"),
            signs = c(1, -1, 1))
# generate the data to be understood by 'thurstonianIRT'
triplets_long <- make_TIRT_data(
  data = triplets, blocks = blocks, direction = "larger",
  format = "pairwise", family = "bernoulli", range = c(0, 1)
)
# fit the data using Mplus
fit <- fit_TIRT_mplus(triplets_long)
**Error in names(x) <- value : 
  'names' attribute [3] must be the same length as the vector [0]**`

**Comment by paul-buerkner** [comment]
Unfortunatley, I don't have access to Mplus anymore, so I cannot really fix this issue myself at the moment. Perhaps you can debug it yourself or ask someone with access to Mplus to take a look? I am sorry that I cannot currently maintain the mplus backend properly.

**Comment by Arizazcq97** [comment]
> 不幸的是，我再也无法访问 Mplus，所以我目前无法自己真正解决这个问题。也许您可以自己调试它或请有权访问 Mplus 的人看看？很抱歉，我目前无法正确维护 mplus 后端。

Well, thank you~
