### ISSUE TITLE
Set a release tag 

### ISSUE THREAD

**Issue by russellpierce** [paul-buerkner/thurstonianIRT#4]
> Version: Does the release version given match the GitHub release (0.9.0)?

Github doesn't have any 'release' set and the current version is 0.9.0.  I see the current version is 0.9.1.  Please consider this issue a TODO to bump version # and tag a release upon completion of the review.

**Comment by paul-buerkner** [comment]
Thank you! Will do.

**Comment by paul-buerkner** [comment]
I bumped the version number to 0.10.0 and added a github release.
