### ISSUE TITLE
make_lavaan_code() creates illegal lavaan syntax

### ISSUE THREAD

**Issue by yrosseel** [paul-buerkner/thurstonianIRT#42]
make_lavaan_code(), as called for example in fit_TIRT_lavaan() creates syntax that looks like this:

`trait1 =~ start(1) * L1 * i1i2 + start(1) * L1 * i1i3 + ...`

However, you can (currently) only have one modifier per lhs element in lavaan syntax. If you wish to add a starting value AND add a label, then you need to write something like `start(1)*i1i2 + L1*i1i2`. So you can repeat the lhs element multiple times, each time with another modifier. 

The old parser in lavaan did not detect this, but the new parser (in the github version) does. Using the github version of lavaan, you can switch between the old and new parser by setting the `parser=` argument in the `lavParseModelString()` function.

**Comment by paul-buerkner** [comment]
Thanks! Should now be fixed.
