### ISSUE TITLE
Note:  Positioning IRT as guard against honesty rather than latent variable extraction

### ISSUE THREAD

**Issue by russellpierce** [paul-buerkner/thurstonianIRT#5]
This is just a reviewer's note for consideration, not a statement that anything need be changed.  Feel free to close this issue once you've considered my comment with or without response on your part.

I'm curious about the decision to position your package primarily as a defense against dishonest participants.  You give only very light coverage of the fact that it is doing latent variable extraction in the paper - and not much at all in the package documentation.  My understanding is that IRT leverages different quality/'difficulty' items to gain a more reasonable 'scale' based estimate of the latent trait than might be possible if only summarizing individual items.  In my domain, at least, that is part of the magic of IRT and in mostly skipping past that part it almost feels as if you are underselling the value of your package.

**Comment by paul-buerkner** [comment]
Good point! I will update the paper and doc accordingly.

**Comment by paul-buerkner** [comment]
I now discuss some general advantages of IRT in both README and paper. Thank you again for this suggestion!
