### ISSUE TITLE
Install Issues on Mac OS

### ISSUE THREAD

**Issue by russellpierce** [paul-buerkner/thurstonianIRT#6]
This looks different than #1 .  On Mac OS (after a successful install of RStan) I got 
```
In file included from stan_files/thurstonian_irt_model.cc:1:
In file included from /Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp/include/Rcpp.h:27:
In file included from /Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp/include/RcppCommon.h:29:
In file included from /Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp/include/Rcpp/r/headers.h:59:
In file included from /Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp/include/Rcpp/platform/compiler.h:100:
In file included from /usr/local/clang7/include/c++/v1/cmath:305:
/usr/local/clang7/include/c++/v1/math.h:301:15: fatal error: 'math.h' file not found
#include_next <math.h>
              ^~~~~~~~
1 error generated.
make: *** [stan_files/thurstonian_irt_model.o] Error 1
rm stan_files/thurstonian_irt_model.cc
ERROR: compilation failed for package ‘thurstonianIRT’
```
When installing from the github repo @ 43ebf97069c9c9069dbc1ea9cdc77659cb38ab2a.  `sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /` a recommended RCpp troubleshooting step cleared that error, but another one occurred ~(for which I'll open another issue)~ (that error looks the same as the one CRAN reports (see next message- so I'm going to skip opening an issue).

Ideally you catch these obtuse errors before they happen and yield instructive error messages to your user.

**Comment by russellpierce** [comment]
This result is also happening for CRAN on older versions of R... https://www.r-project.org/nosvn/R.check/r-oldrel-osx-x86_64/thurstonianIRT-00check.html.  So, it may be that you need to update your DESCRIPTION to limit installs to at least >= 3.5.3 (which is what I'm running... CRAN is checking vs 3.5.2), but to be safe probably >= 3.6.0 (which is what is passing on CRAN).

**Comment by paul-buerkner** [comment]
Thanks! This is most likely an rstan issue which will be impossible to fix (or even catch) from the thurstonianIRT side. I will probably need to update the version requirements just to be save.

**Comment by paul-buerkner** [comment]
R version requirement is no 3.6.0
