### ISSUE TITLE
Clarification Request: Documentation Clarity around 'blocks'

### ISSUE THREAD

**Issue by russellpierce** [paul-buerkner/thurstonianIRT#7]
This is a clarification I need in order to review your work.  You need not act/change anything in response to this item (yet). But, please respond so the review may continue.

Please be patient/keep in mind that it's been a (long) while since I reached for IRT so I'm somewhat fuzzy.

In `sim_TIRT_data()` you have args `nblocks_per_trait` and `nitems_per_block`.  A 'block' might be a term of art associated with your area of work / the tradition you've learned IRT from... but from your documentation alone I'm not sure what it means/is meant to signify.  Based on the description in `set_block`, it almost sounds like the function just establishes the assignment of items to traits (and whether the item is reverse coded).  But, if that is all that was going on, then I'd expect (for your example) the block definition...

```r
blocks_2 <-
  set_block(
    paste0("i",1:12),
    paste0("t",rep(1:3, 4)),
    signs =c(1,1,1,-1,1,1,1,1,-1,1,-1,1)
  )
```

...to work.  But it doesn't.  Can you tell me more about what is going on with 'blocks' and why a design with a single block is invalid (make_TIRT_data doesn't seem to execute with a single block)?

My brief Google effort suggested it is relevant for specifying designs where each observational unit might have only seen a subset of blocks (aka item sets)... but that seems more like a special/edge case rather than the default/simple case... no?

**Comment by paul-buerkner** [comment]
Apologies for being unclear with this. A block is a set of items being compared in a forced choice/ranking format. For instance, if participants are asked to rank the items

(1) I like to go to parties
(2) I am always on time
(3) I am emotionally stable

into an order from 1 to 3 (how much they relate to them), then these 3 items form a block.

I will clarify this in the doc tomorrow.

**Comment by russellpierce** [comment]
My mind is a little blown because I've only operated in the much narrower world where each item was forced choice between two options.  So, I'm going to have a sit and think to see if I can reorient myself.  Thanks for the quick answer!

**Comment by paul-buerkner** [comment]
I have updated the documentation of `set_block` which now reads:

"Prepare blocks of items and incorporate information about which item belongs to which trait. A block of items is a set of two or more items presented and answered together by fully ranking them or selecting the most and/or least favorit in a forced choice format. A whole test usually contains several blocks and items may reappear in different blocks."
